version: "3.6"
services:
  jenkins-dev.mycrop.com:
    image: jenkinsci/blueocean:1.8.4
    hostname: jenkins-dev.mycrop.com
    user: root
    privileged: true
    expose:
      - 8080
    volumes:
      - ~/:/home
      - /app/jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.m2:/root/.m2
    environment:
      - VIRTUAL_HOST=jenkins-dev.mycrop.com
      - VIRTUAL_PORT=8080
    deploy:
      resources:
          limits:
              cpus: "2"
              memory: 2048M
      restart_policy:
          condition: always
  gitlab.mycrop.com:
    image: gitlab/gitlab-ce:11.4.7-ce.0
    hostname: gitlab.mycrop.com
    user: root
    privileged: true
    expose:
      - 22
      - 80
      - 443
    volumes:
      - /app/gitlab_home/data:/var/opt/gitlab
      - /app/gitlab_home/logs:/var/log/gitlab
      - /app/gitlab_home/config:/etc/gitlab
    environment:
      - VIRTUAL_HOST=gitlab.mycrop.com
      - VIRTUAL_PORT=80
    deploy:
      resources:
          limits:
              cpus: "2"
              memory: 4096M
      restart_policy:
          condition: always
  sonarqube.mycrop.com:
    image: sonarqube:6.7-community
    hostname: sonarqube.mycrop.com
    privileged: true
    expose:
      - 9000
    volumes:
      - /app/sonarqube_home/conf:/opt/sonarqube/conf
      - /app/sonarqube_home/data:/opt/sonarqube/data
      - /app/sonarqube_home/logs:/opt/sonarqube/logs
      - /app/sonarqube_home/extensions:/opt/sonarqube/extensions
    environment:
      - VIRTUAL_HOST=sonarqube.mycrop.com
      - VIRTUAL_PORT=9000
    deploy:
      resources:
          limits:
              cpus: "2"
              memory: 2048M
      restart_policy:
          condition: always
  devops-nginx.mycrop.com:
    image: jwilder/nginx-proxy:alpine
    hostname: devops-nginx.mycrop.com
    user: root
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /app/reverse-proxy:/etc/nginx/certs:ro
    deploy:
      resources:
          limits:
              cpus: "1"
              memory: 2048M
      restart_policy:
          condition: always
  dependency-track.mycrop.com:
    image: owasp/dependency-track:3.3.1
    hostname: dependency-track.mycrop.com
    user: root
    privileged: true
    expose:
      - 8080
    volumes:
      - /app/dependencytrack_home/data/:/data
    environment:
      - VIRTUAL_HOST=dependency-track.mycrop.com
      - VIRTUAL_PORT=8080
networks:
  default:
    external:
      name: devopsnet
